### ISSUE TITLE
Add instructions to force add `config/secrets.yml`?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/rails-api-template#13]
Or remove `config/secrets.yml` from `.gitignore`?

@ga-wdi-boston/core

**Comment by J-Weeks** [comment]
It's reference in a pending pull request for the deployment guide https://github.com/ga-wdi-boston/rails-deployment-heroku-study/pull/16 I like the idea of having them force add it. It adds a layer of "this is really important" to the process.

**Comment by gaand** [comment]
@J-Weeks #8 required removing from `.gitignore` (and also closes this issue).  I'll open one on the deployment guide.
