### ISSUE TITLE
Error message when making POST request

### ISSUE THREAD

**Issue by andreasantarl** [ga-wdi-boston/rails-api-template#19]
When I make a POST request to create a new user profile, I get an error message: 
localhost/:1 XMLHttpRequest cannot load http://localhost:3000/profiles. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 400.

My other CRUD works (the template that we were given).

**Comment by jrhorn424** [comment]
Is this tracked elsewhere? @ga-wdi-boston/core

**Comment by gaand** [comment]
@jrhorn424 It probably should have been [here](/ga-wdi-boston/full-stack-project/issues)

@andreasantarl Was this resolved? If not, please open a new issue at the above link and close here.  Otherwise, please just close here.  Thanks.

**Comment by gaand** [comment]
Since @andreasantarl hasn't responded, I am closing this issue ( @jrhorn424 we'd need more information to address this if that is actually needed).
