### ISSUE TITLE
Instruction clarification

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/rails-api-template#23]
1.  Store them in `.env` with keys `SECRET_KEY_BASE_<DEVELOPMENT|TEST>`
   respectively.
   to
2.  Store them in `.env` with keys `SECRET_KEY_BASE_DEVELOPMENT=<newly created secret>`
   and a new secret for `SECRET_KEY_BASE_TEST`.

**Comment by raq929** [comment]
@gaand convinced me that we should not do this for philosophical reasons, namely, developers will have to learn how to read documentation, and this is good practice for them. Also, we will have done this several times in class. 

I want to leave this issue open - if it continues to be a problem for a lot of people, I would advocate for something like:

Store them in `.env` with keys `SECRET_KEY_BASE_<DEVELOPMENT|TEST>`
   respectively. (You should have *two* keys `SECRET_KEY_BASE_DEVELOPMENT=<newly created secret>` and `SECRET_KEY_BASE_TEST`

**Comment by gaand** [comment]
@payne-chris-r I believe that 730e35e40286e1e076962127730dad72f96c0439 and 9e96cf0d84152cb75c78040919941486ee125eeb are sufficient clarification.

**Comment by payne-chris-r** [comment]
Looks good to me. We'll see how many of them screw it up and reopen/open a new one if it's still unclear...
