### ISSUE TITLE
Edit scripts for right url

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/rails-api-template#28]
currently pointing to `localhost:3000`, needs to be `localhost:4741`

**Comment by raq929** [comment]
I believe this was addressed in:
d98539796e5b2273c7397af0a85f1e045231cc96

@gaand can you confirm?

**Comment by gaand** [comment]
No.  This refers to the the shell scripts in `scripts/`.  The ports used still need to be corrected.
