### ISSUE TITLE
Remove boilerplate comments from `config/secrets.yml`

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/rails-api-template#29]
Instead of setting env variables in `secrets.yml` (and risk committing them by mistake), set them via the terminal? 
`export SECRET_KEY_BASE_DEVELOPMENT=<secret>`

**Comment by raq929** [comment]
So consider adding that to the secrets instructions. As well as how to test that your env variables are set: `echo $SECRET_KEY_BASE_DEVELOPMENT`

**Comment by BenGitsCode** [comment]
I really like this method, both personally and as a safer insurance policy for developers pushing their secrets. Curious as to what @gaand and @payne-chris-r think about this.

**Comment by gaand** [comment]
Have you read the README?  We don't set anything in `secrets.yml`

Nothing goes in the shell environment, either.  What you are suggesting is an anti-pattern leading to bugs and other unanticipated severe consequences.

Putting the environment variables in `.env` ensures per repository secrets that are only available to the running app.

**Comment by raq929** [comment]
The issue is that in the repos that update from this template, `.env` is never mentioned, and they say to follow instructions in `config/secrets.yml`.
In `secrets.yml`, `.env` is not mentioned either, so it seems like secrets ought to be updated in `secrets.yml`. I have changed the instructions in `secrets.yml` in the repos I'm updating. (`rails-api`, `rails-api-single-resource`).
I also realized after suggesting this that I've only done it that way when I'm working on a virtual env, which we are not, so I agree we should not do this in the terminal.

**Comment by gaand** [comment]
That's a problem with those repositories, not this one.

`.env` should be used for secrets.

**Comment by gaand** [comment]
This repository,as the template, should be considered authoritative.  If it's not, we have to fix it here.  In this case, it is.  All of the rails-apis we create and run locally should use secrets from `.env`

**Comment by gaand** [comment]
The comments at the top of `config/secrets.yml` should be replaced with a comment about using `.env` to hold secrets.
