### ISSUE TITLE
Remove extraneous bin/rake db:migrate VERSION=0

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/rails-api-template#39]
From right above the license.

**Comment by gaand** [comment]
I'm not sure why you think it's extraneous.  I just looked and it's not.

https://github.com/ga-wdi-boston/rails-api-template#reset-database-without-dropping

**Comment by jrhorn424** [comment]
<img width="608" alt="ga-wdi-boston_rails-api-template__a_template_for_starting_projects_with_ rails-api" src="https://cloud.githubusercontent.com/assets/388761/21272441/48ae8dba-c38d-11e6-816b-6aad4ef452a3.png">
