### ISSUE TITLE
error on rails setup, when running rails db:nuke_pave, or when querying from frontend

### ISSUE THREAD

**Issue by ioncrash** [ga-wdi-boston/rails-api-template#44]
so I've been working on a very simple app for a coding challenge, following the instructions on rails-api-template. Never had problems with it before, but now when I get to the line `bundle exec rake db:nuke_pave` I get this

```
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

followed by a long list of what look like paths to files. At the end of all of it, it says

```
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"book-list-back_test"}
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
/Users/pygartheangel/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/pygartheangel/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:nuke_pave => db:migrate
(See full trace by running task with --trace)
```

not sure where to start. Thanks in advance

**Comment by gaand** [comment]
@ioncrash This is not an issue with this repository.  It's an issue with the PostgeSQL server.

I believe there are closed issues about this on both the capstone and full-stack-project repositories.  

Please close this issue and if after reviewing those other issues you still need assistance open an issue  on capstone or portfolio as appropriate.
